### ISSUE TITLE
Doesn't seem to work (Windows)

### ISSUE THREAD

**Issue by mrmckeb** [DannyMoerkerke/brackets-selections#1]
I installed this, restarted Brackets, still nothing. Perhaps I'm missing something?

**Comment by DannyMoerkerke** [comment]
I will need some more information to solve this problem. It might be Windows related, do you see any errors in developer tools?

**Comment by DannyMoerkerke** [comment]
I'm an idiot, forgot to add keybindings for Linux and Windows. Could you please try again?

**Comment by mrmckeb** [comment]
Great, it seems to work now - although I should point out that Ctrl+Shift+Up/Down is already used by brackets for moving lines up and down.

Perhaps Ctrl+Shift+Page Up/Down?

Ctrl+Shift+J seems to mostly work in HTML too. Are you planning to support HTML tags fully?

It works great in JS/CSS, so again, thanks.

**Comment by DannyMoerkerke** [comment]
Sure, keybindings can be assigned per platform so I'll change that. If I remember correctly moving lines up and down also works like that on Linux, only OSX is Ctrl-Cmd-Up/Down.
I'll check if Page Up/Down is "available".
Selecting matching tags is a bit trickier since, as far as I could see, it is not provided by the underlying CodeMirror editor in Brackets (CodeMirror standalone does provide it though) and I'd have to implement it myself.
Of course that can be done but requires some more work. The main reason I did not provide it is that it is already provided by Emmet, but maybe I'll implement it soon anyway.

Thanks for trying!
